version: "3.9"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    restart: always

  server:
    build: ./server
    ports:
      - 5001:5000
    volumes:
      - ./server:/app
    restart: always