# Generated by Django 4.1.3 on 2022-11-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=99999, primary_key=True, serialize=False)),
                ('password', models.CharField(default='none', max_length=99999)),
                ('ratings', models.JSONField(default='')),
            ],
        ),
    ]
