# Generated by Django 4.1.3 on 2022-11-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('Name', models.CharField(default='not found', max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
