# Generated by Django 4.1.3 on 2022-11-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anifind_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='UserID',
        ),
    ]
