# Generated by Django 4.1.3 on 2022-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anifind_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(default='not found', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='not found', max_length=99999),
        ),
    ]
